stages:

  - pull_request
 

pull_request:
  stage: pull_request
  script:
    - echo "Running PR stage"
    - dotnet restore Myb.sln
    - dotnet build
    - dotnet test
  only:
    - merge_requests
 