variables:
  IMAGE_NAME: "bassem001/tester_myb"  # Docker Hub registry
  IMAGE_TAG: 1.0

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script:
- ssh -o StrictHostKeyChecking=no -i $SSH_KEY ubuntu@51.91.101.8 "
        docker login -u $REGISTRY_USER -p $REGISTRY_PASS &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 5000:5000 $IMAGE_NAME:$IMAGE_TAG"

  dependencies:
    - build 
  only:
    - main
